export const subjects = [
  {
    id: 0,
    subject: 'gt',
    name: 'Graph Theory',
    periods: [24, 33, 42, 51],
    faculty: 'Dr. Susanth C (SC)',
    slot: 'A',
    subjectCode: 'MAT 206 ',
    classroomLink: 'https://classroom.google.com/c/MzI2MDUxMDI4Mzkw',
    meetLink: 'https://meet.google.com/lookup/ea6uhdtjbn?authuser=0&hs=179',
  },
  {
    id: 1,
    subject: 'coa',
    name: 'Computer Organization and Architecture',
    periods: [14, 21, 32, 44],
    faculty: 'Shameem S (SS)',
    slot: 'B',
    subjectCode: 'CST 202',
    classroomLink: 'https://classroom.google.com/c/MzI2MDQ5MDY3NjU1',
    meetLink: 'https://meet.google.com/lookup/fgohtz74gy?authuser=0&hs=179',
  },
  {
    id: 2,
    subject: 'dms',
    name: 'Data Base Managment System',
    periods: [11, 22, 34, 53],
    faculty: 'Jucy Vareed (JV)',
    slot: 'C',
    subjectCode: 'CST 204',
    classroomLink: 'https://classroom.google.com/c/MzI2MDQ5MDY3NzYw',
    meetLink: 'https://meet.google.com/lookup/fl62oqn4kb?authuser=0&hs=179',
  },
  {
    id: 3,
    subject: 'os',
    name: 'Operating Systems',
    periods: [13, 23, 31, 41],
    faculty: 'Nakulraj K R (NKR)',
    slot: 'D',
    subjectCode: 'CST 206',
    classroomLink: 'https://classroom.google.com/c/MzI2MDQ5MDY3ODU2',
    meetLink: 'https://meet.google.com/lookup/gzoosfb3cq?authuser=0&hs=179',
  },
  {
    id: 4,
    subject: 'pe',
    name: 'Professional Ethics',
    periods: [43, 52],
    faculty: 'Athira P S(APS)	',
    slot: 'E',
    subjectCode: 'HUT 200',
    classroomLink: 'https://classroom.google.com/c/MzI2MDUxMDM3NjM5',
    meetLink: 'https://meet.google.com/lookup/fs2hwqvcqf?authuser=0&hs=179',
  },
  {
    id: 5,
    subject: 'ci',
    name: 'Constitution of India',
    periods: [12, 54],
    faculty: 'Sonia Rose C P (SRCP)',
    slot: 'F',
    subjectCode: 'MCN 202',
    classroomLink: 'https://classroom.google.com/c/MzI2MDUwMDI3MDQx',
    meetLink: 'https://meet.google.com/lookup/f55pnueayr?authuser=0&hs=179',
  },
  {
    id: 6,
    subject: 'digital-lab',
    name: 'Digital Lab',
    periods: [25],
    faculty: 'Remya Rajendran (RR), Honey Mol P K (HPK)',
    slot: 'S',
    subjectCode: 'CSL 202',
    classroomLink: 'https://classroom.google.com/c/MzI2MDUzMzExMjEz',
    meetLink: 'https://meet.google.com/lookup/a5sopjb25y?authuser=0&hs=179',
  },
  {
    id: 7,
    subject: 'os-lab',
    name: 'Operating Systems Lab',
    periods: [15],
    faculty: 'Nakulraj K R (NKR), Jucy Vareed (JV)',
    slot: 'T',
    subjectCode: 'CSL204',
    classroomLink: 'https://classroom.google.com/c/MzI2MDU0NTQ2NDA2',
    meetLink: 'https://meet.google.com/lookup/fovzsojpz4?authuser=0&hs=179',
  },
  {
    id: 8,
    subject: 'cfml',
    name: 'Computational Fundamentals for Machine Learning',
    periods: [61, 62],
    faculty: 'Thulasi Rajan K(TRK)',
    slot: 'u',
    subjectCode: 'CST294',
    classroomLink: '',
    meetLink: '',
  },
];

// GT
// COA
// DMS
// OS
// PE
// CI
// DIGITAL-LAB
// OS-LAB
// CFML
